[package]
name = "color_cycle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lockjaw = "*"
cubit = "*"
cubit-win64 = "*"
winapi = "*"

[build-dependencies]
lockjaw = "*"