[package]
name = "compile_tests"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
trybuild = { git = "https://github.com/azureblaze/trybuild" }
lockjaw = { path = "../" }